# Generated by Django 5.2 on 2025-06-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistas_quillayquen', '0002_delete_cotizacion_remove_reserva_fecha_and_more'),
    ]

    operations = [
    ]
